version: '2'
services:
  jenkins:
    image: 'atlassian/bitbucket-server:7.2.0-ubuntu'
    ports:
      - '7990:7990'
      - '7999:7999'
    volumes:
      - 'bitbucketVolume:/var/atlassian/application-data/bitbucket'
volumes:
  bitbucketVolume:
    driver: local
