#!/bin/groovy
pipeline {
  agent any
 
  tools {nodejs "node"}

  stages {
    stage('Startup') {
      steps {
        script {
          sh 'npm i --registry http://10.7.6.60:4873'
        }
      }
    }
    stage('Test') {
      steps {
        script {
          sh 'npm run test:coverage'
        }
      }
      post {
        always {
          step([$class: 'CoberturaPublisher', coberturaReportFile: 'output/coverage/jest/cobertura-coverage.xml'])
        }
      }
    }
  }
}