apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonarqube
  template:
    metadata:
      name: sonarqube
      labels:
        name: sonarqube
    spec:
      containers:
        - image: gqy117/sonarqube-dependency-check
          name: sonarqube
          env:
            - name: sonar.jdbc.username
              value: sonar
            - name: sonar.jdbc.password
              value: sonar
            - name: sonar.jdbc.url
              value: jdbc:postgresql://sonar-postgres:5432/sonar

            # - name: SONARQUBE_JDBC_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: postgres-pwd
            #       key: password
            # - name: SONARQUBE_JDBC_URL
            # - name: SONARQUBE_JDBC_PASSWORD
            #   value: sonar
            # - name: SONARQUBE_JDBC_URL
            #   value: jdbc:postgresql://sonar-postgres:5432/sonar
          ports:
            - containerPort: 9000
              name: sonarqube
          resources:
            requests:
              memory: 2000Mi
            limits:
              memory: 2000Mi
      initContainers:
        - name: sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true